apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-is
  namespace: "api-first-workshop"
data:
  application.properties: |
    healthindicators.Adapters.enabled=true
    healthindicators.Cluster.enabled=true
    healthindicators.Cluster.properties.threshold.value=2
    healthindicators.Diskspace.enabled=true
    healthindicators.Diskspace.properties.threshold.value=10
    healthindicators.JDBC.enabled=true
    healthindicators.JMS.enabled=true
    healthindicators.JNDIAliases.enabled=false
    healthindicators.Memory.enabled=true
    healthindicators.Memory.properties.threshold.value=10
    healthindicators.RemoteServers.enabled=true
    healthindicators.SFTPServers.enabled=true
    healthindicators.ServiceThread.enabled=true
    healthindicators.ServiceThread.properties.threshold.value=10
    healthindicators.Sessions.enabled=true
    healthindicators.Sessions.properties.threshold.value=85
    healthindicators.UMAliases.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://universalmessaging.swag-infra\:9000
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "${CONTAINER}"
  namespace: "api-first-workshop"
  labels:
    app: "${CONTAINER}"
spec:
  selector:
    matchLabels:
      app: "${CONTAINER}" 
  template: 
    metadata:
      labels:
        app: "${CONTAINER}"
    spec:
      containers:
        - name: "${CONTAINER}"
          image: "${REGISTRY}/${CONTAINER}:${CONTAINER_TAG}"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/swagmsr/config
            - name: license-file
              mountPath: /opt/softwareag/IntegrationServer/config/licenseKey.xml
              subPath: ISLicense.xml
          env:
            - name: "SAG_IS_CONFIG_PROPERTIES"
              value: "/opt/swagmsr/config/application.properties"
#        - name: "api-micro-gateway"
#          image: "softwareag/microgateway-trial:10.11"
#          ports:
#            - containerPort: 9090
#              protocol: "TCP"
#          env:
#            - name: "mcgw_api_gateway_url"
#              value: "http://apigateway.swag-infra:5555"
#            - name: "mcgw_api_gateway_user"
#              value: "Administrator"
#            - name: "mcgw_api_gateway_password"
#              value: "manage"
#            - name: "mcgw_downloads_apis"
#              value: "${CONTAINER}"
      volumes:
        - name: config-volume
          configMap:
            name: application-properties-is
        - name: license-file
          configMap:
            name: msr-license
  replicas: 1