apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-is
  namespace: "api-first-workshop"
data:
  application.properties: |
    artConnection.ConnectedDemosTCDB.ConnectedDemosTCDB.connections.ConnectedDemoStore.connectionEnabled=true
    wmcloudsettings.EMEAPresalesTenant.password={AES}3spFzIcsax5C5yfRNlwMGw==
    healthindicators.Adapters.enabled=true
    healthindicators.Cluster.enabled=true
    healthindicators.Cluster.properties.threshold.value=2
    healthindicators.Diskspace.enabled=true
    healthindicators.Diskspace.properties.threshold.value=10
    healthindicators.JDBC.enabled=true
    healthindicators.JMS.enabled=true
    healthindicators.JNDIAliases.enabled=false
    healthindicators.Memory.enabled=true
    healthindicators.Memory.properties.threshold.value=10
    healthindicators.RemoteServers.enabled=true
    healthindicators.SFTPServers.enabled=true
    healthindicators.ServiceThread.enabled=true
    healthindicators.ServiceThread.properties.threshold.value=10
    healthindicators.Sessions.enabled=true
    healthindicators.Sessions.properties.threshold.value=85
    healthindicators.UMAliases.enabled=true
    globalvariable.ConnectedDemos..config..dir.value=/data
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://universalmessaging.swag-infra\:9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wmpublic-config
  namespace: "api-first-workshop"
data:
  fileAccessControl.cnf: |
    allowedReadPaths=/data
    allowedWritePaths=
    allowedDeletePaths=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demodata
  namespace: "api-first-workshop"
data:
  ProductData.json: |
    {
        "dataLoad": {
            "Metadata": [{
                    "version": 1.1,
                    "description": "Demo Master Product Data",
                    "industryType": "",
                    "usedInDemos": "",
                    "lastModifiedBy": "",
                    "lastModifiedDate": "2018-08-22T00:00:00+0100",
                    "reasonsForThisVersionOrIndustryType": "None",
                    "comments": ""
                }
            ],
            "Inventory": [{
                    "id": "INVT-001",
                    "productId": "PROD00001",
                    "locationId": "LOC00018",
                    "batchId": "",
                    "quantity": 26.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-002",
                    "productId": "PROD00004",
                    "locationId": "LOC00005",
                    "batchId": "",
                    "quantity": 3.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-003",
                    "productId": "PROD00002",
                    "locationId": "LOC00018",
                    "batchId": "",
                    "quantity": 0.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-004",
                    "productId": "PROD00003",
                    "locationId": "LOC00018",
                    "batchId": "",
                    "quantity": 35.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-005",
                    "productId": "PROD00004",
                    "locationId": "LOC00018",
                    "batchId": "",
                    "quantity": 20.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-006",
                    "productId": "PROD00005",
                    "locationId": "LOC00018",
                    "batchId": "",
                    "quantity": 28.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-007",
                    "productId": "PROD00002",
                    "locationId": "LOC00005",
                    "batchId": "",
                    "quantity": 16.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }, {
                    "id": "INVT-008",
                    "productId": "PROD00001",
                    "locationId": "LOC00005",
                    "batchId": "",
                    "quantity": 0.0,
                    "serialNumber": "",
                    "inventoryTypeId": "REFINV-01"
                }
            ],
            "SalesOrder": [
                {
                    "id": "SAL0000021",
                    "customerId": "0010900000FcMy8AAF",
                    "statusId": "STAT0001",
                    "totalValue": 13.95,
                    "orderDate": "2019-08-22T13:18:00+0100",
                    "shipDate": "2019-08-22T13:21:00+0100",
                    "isUrgent": false,
                    "currencyId": "EUR",
                    "processTypeId": "PROC00002",
                    "orderItemCount": 1
                }
            ],
            "SalesOrderItem": [
                {
                    "id": "SAL0000021-001",
                    "orderId": "SAL0000021",
                    "productId": "PROD00002",
                    "statusId": "STAT005",
                    "quantity": 1.0,
                    "price": 11.00,
                    "totalValue": 13.95,
                    "currencyId": "EUR"
                },
                {
                    "id": "SAL0000021-002",
                    "orderId": "SAL0000021",
                    "productId": "PROD00003",
                    "statusId": "STAT005",
                    "quantity": 1.0,
                    "price": 2.95,
                    "totalValue": 13.95,
                    "currencyId": "EUR"
                }
            ],
            "Product": [{
                    "id": "PROD00001",
                    "productName": "Millennium Falcon",
                    "productDescription": "YT-1300 light freighter",
                    "manufacturerId": "MNFR_014",
                    "purchaseCost": 14000.0,
                    "listPrice": 15450.0,
                    "productTypeId": "PRO-CAT-004",
                    "UOMTypeId": "UOM-001",
                    "merchandiseId": "MERCH-001",
                    "currencyId": "CUR-001",
                    "brandId": "BRD-004",
                    "imageId": "PROD00001-MD",
                    "bestBeforeDate": ""
                }, {
                    "id": "PROD00002",
                    "productName": "Death Star",
                    "productDescription": "DS-1 Orbital Battle Station",
                    "manufacturerId": "MNFR_014",
                    "purchaseCost": 6000.0,
                    "listPrice": 8500.0,
                    "productTypeId": "PRO-CAT-004",
                    "UOMTypeId": "UOM-001",
                    "merchandiseId": "CVFFRC8911",
                    "currencyId": "CUR-001",
                    "brandId": "BRD-004",
                    "imageId": "PROD00002-MD",
                    "bestBeforeDate": ""
                }, {
                    "id": "PROD00003",
                    "productName": "Y-wing",
                    "productDescription": "Koensayr BTL Y-wing",
                    "manufacturerId": "MNFR_014",
                    "purchaseCost": 15999.0,
                    "listPrice": 17250.0,
                    "productTypeId": "PRO-CAT-003",
                    "UOMTypeId": "UOM-001",
                    "merchandiseId": "HYHYAA8812",
                    "currencyId": "CUR-001",
                    "brandId": "BRD-004",
                    "imageId": "PROD00003-MD",
                    "bestBeforeDate": ""
                }, {
                    "id": "PROD00004",
                    "productName": "X-wing",
                    "productDescription": "Incom Corporation T-65 X-wing",
                    "manufacturerId": "MNFR_014",
                    "purchaseCost": 14340.0,
                    "listPrice": 15000.0,
                    "productTypeId": "PRO-CAT-004",
                    "UOMTypeId": "UOM-001",
                    "merchandiseId": "CVXXXC3312",
                    "currencyId": "CUR-001",
                    "brandId": "BRD-004",
                    "imageId": "PROD00004-MD",
                    "bestBeforeDate": ""
                }, {
                    "id": "PROD00005",
                    "productName": "TIE Advanced x1",
                    "productDescription": "Sienar Fleet Systems Twin Ion Engine Advanced x1",
                    "manufacturerId": "MNFR_014",
                    "purchaseCost": 15500.0,
                    "listPrice": 16245.0,
                    "productTypeId": "PRO-CAT-004",
                    "UOMTypeId": "UOM-001",
                    "merchandiseId": "BHWSQQ9822",
                    "currencyId": "CUR-001",
                    "brandId": "BRD-004",
                    "imageId": "PROD00005-MD",
                    "bestBeforeDate": ""
                }
            ]
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasetnames
  namespace: "api-first-workshop"
data:  
  dataSetNames.txt: |
    Inventory/Product/SalesOrderItem/SalesOrder/UOM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productapicloudconfig
  namespace: api-first-workshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "products-api"
  namespace: "api-first-workshop"
  labels:
    app: "products-api"
spec:
  selector:
    matchLabels:
      app: "products-api" 
  template: 
    metadata:
      labels:
        app: "products-api"
    spec:
      containers:
        - name: "products-api"
          image: "${REGISTRY}/products-api:1.0.${BUILD_NUMBER}"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - name: config-volume
              mountPath: /opt/swagmsr/config
            - name: data-volume
              mountPath: /data
            - name: data-set-names
              mountPath: /data/utils/dataSet
            - name: wmpublic-config
              mountPath: /opt/softwareag/IntegrationServer/instances/default/packages/WmPublic/config/fileAccessControl.cnf
              subPath: fileAccessControl.cnf
            - mountPath: /opt/softwareag/IntegrationServer/instances/default/config/integrationlive
              name: is-cloud-config  
          env:
            - name: "SAG_IS_CONFIG_PROPERTIES"
              value: "/opt/swagmsr/config/application.properties"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: application-properties-is
        - name: data-volume
          configMap:
            name: demodata
        - name: wmpublic-config
          configMap:
            name: wmpublic-config
        - name: data-set-names
          configMap:
            name: datasetnames
        - name: license-file
          configMap:
            name: msr-license
        - name: is-cloud-config
          persistentVolumeClaim:
            claimName: productapicloudconfig
  replicas: 1