pipeline {

	agent {
		kubernetes {
    	label 'docker-builder'
    	defaultContainer 'jnlp'
    	yaml """
kind: Pod
spec:
  serviceAccountName: jenkins-agent-account
  containers:
  - name: jnlp
    workingDir: /tmp/jenkins
  - name: dind
    workingDir: /tmp/jenkins
    image: docker
    imagePullPolicy: Always
    restartPolicy: Never
    command: 
    - /bin/cat
    tty: true
    volumeMounts:
    - name: tmp-dir
      mountPath: /wm-installer
    - name: docker-sock
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
  volumes:
  - name: docker-sock
    hostPath:
      path: "/var/run/docker.sock"
"""
		}
	}
	
	parameters{
		string(name: 'REGISTRY_INGRESS', defaultValue: 'https://registry.master.servers', description: 'Endpoint of the docker registry')
	}

	environment {
        JAVA_HOME = "/opt/softwareag/jvm/jvm"
		PACKAGE = "Products"
		NAMESPACE = "api-first-workshop"
		REGISTRY = "${params.REGISTRY_INGRESS}"
		CONTAINER = "products_api"
		CONTAINER_TAG = "1.0"
    }

    stages {
        stage('Prepare'){
            steps {
				dir("${PACKAGE}") {
					sh 'mkdir build \
						build/repo \
						build/container \
						dist'
					sh 'mv config build/container'

					sh 'cd build/container; \
					    cp -r ${WORKSPACE}/${PACKAGE}/Dockerfile .; \
						cp -r ${WORKSPACE}/${PACKAGE}/src/IS/${PACKAGE} .; \
						cp -r ${WORKSPACE}/${PACKAGE}/src/IS/ConnectedDemos .; \
						cp -r ${WORKSPACE}/${PACKAGE}/src/IS/ConnectedDemosTCDB .;'

				}
			}
		}

		stage('Build') {
			steps {
				container(name: 'dind', shell: '/bin/sh') {
					sh '''#!/bin/sh
            			cd ${PACKAGE}
            		'''
					script {
						docker.withRegistry("${REGISTRY}") {
					
						def customImage = docker.build("${PACKAGE}:${CONTAINER_TAG}", "${PACKAGE} --build-arg BASE_IMAGE=microservice-runtime-tcdb:10.11 --build-arg PACKAGE=${PACKAGE}")

						/* Push the container to the custom Registry */
						customImage.push()
					}
				}
			}
		}
		
/*		stage('Test') {
			steps {
				container(name: 'kaniko', shell: '/busybox/sh') {
					sh 'cd ${WORKSPACE}/${PACKAGE}/test; \
						/opt/softwareag/common/lib/ant/bin/ant -f run-composite-runner.xml -propertyfile run-test.properties composite-runner-all-tests'
					junit '**/build/test/reports/*.xml'
				}
			}
		}
*/
		stage('Deploy-Container'){
            steps {
				container(name: 'kaniko', shell: '/busybox/sh') {
					withKubeConfig([credentialsId: 'systemadmin', serverUrl: 'https://kubernetes.default']) {
						sh 'kubectl apply -f ${PACKAGE}/deployment/${CONTAINER}-DC.yml'
				
						script {
							try {
								sh 'kubectl -n ${NAMESPACE} get service ${CONTAINER}-service'
							} catch (exc) {
								echo 'Service does not exist yet'
								sh 'kubectl apply -f ${PACKAGE}/deployment/${CONTAINER}-service-route.yml'
							}
						}
					}
				}
            }
        }
    }
}
