pipeline {
	agent {
		kubernetes {
    	label 'docker-builder'
    	defaultContainer 'jnlp'
    	yaml """
kind: Pod
spec:
  serviceAccountName: jenkins-agent-account
  containers:
  - name: jnlp
    workingDir: /tmp/jenkins
  - name: dind
    workingDir: /tmp/jenkins
    image: registry.k8s/kaniko:tini
    imagePullPolicy: Always
    restartPolicy: Never
    command: 
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
    - name: tmp-dir
      mountPath: /wm-installer
  volumes:
  - name: tmp-dir
    hostPath:
      path: "/tmp/license"
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: regcred 
          items:
            - key: .dockerconfigjson
              path: config.json 
"""
		}
	}

		
	parameters{
		string(name: 'REGISTRY', defaultValue: 'registry.master.servers', description: 'Endpoint of the docker registry')
		string(name: 'HOST', description: 'Base hostname of your cloud machine for the ingress')
	}

	environment {
		PACKAGE = "Machines"
		NAMESPACE = "api-first-workshop"
		REGISTRY_INGRESS = "https://${params.REGISTRY}"
		CONTAINER = "machine-status-api"
		CONTAINER_TAG = "1.0.${env.BUILD_NUMBER}"
    }

    stages {
	stage('Prepare'){
            steps {
				dir("${PACKAGE}") {
					sh 'mkdir build \
						build/repo \
						build/container \
						dist \
						build/test \
						build/test/reports'
					sh 'mv config build/container'
					sh 'mv Listeners build/container'
					sh 'mv acls build/container'
					sh 'chmod -R go+w build/test; \
						chmod go+w test'
					sh 'cd build/container; \
					    cp -r ${WORKSPACE}/${PACKAGE}/Dockerfile .; \
						cp -r ${WORKSPACE}/${PACKAGE}/src/IS/${PACKAGE} .;'
				}
			}
		}

    stage('Build'){
      steps {
				container(name: 'dind', shell: '/bin/sh') {
					sh '''#!/bin/sh
            			cd ${PACKAGE}
            		'''
					script {
						sh '''#!/busybox/sh
						echo "building ${REGISTRY}/${CONTAINER}:${CONTAINER_TAG}"
            /kaniko/executor --context ${PACKAGE}/build/container \
              --destination ${REGISTRY}/${CONTAINER}:${CONTAINER_TAG} \
              --destination ${REGISTRY}/${CONTAINER}:${CONTAINER_TAG}.${BUILD_NUMBER} \
              --destination ${REGISTRY}/${CONTAINER}:latest \
              --skip-tls-verify \
							--build-arg BASE_IMAGE=microservice-runtime-tcdb:10.11 \
							--build-arg PACKAGE=${PACKAGE}
						'''
					}
				}
			}
		}
	stage('Deploy-Container'){
            steps {
				container(name: 'dind', shell: '/bin/sh') {
					withKubeConfig([credentialsId: 'jenkins-agent-account', serverUrl: 'https://kubernetes.default']) {
						sh '''#!/bin/sh
						cat ${PACKAGE}/deployment/api-DC.yml | sed --expression='s/${CONTAINER}/'$CONTAINER'/g' | sed --expression='s/${REGISTRY}/'$REGISTRY'/g' | sed --expression='s/${CONTAINER_TAG}/'$CONTAINER_TAG'/g' | kubectl apply -f -'''
				
						script {
							try {
								sh 'kubectl -n ${NAMESPACE} get service ${CONTAINER}-service'
							} catch (exc) {
								echo 'Service does not exist yet'
								sh '''cat ${PACKAGE}/deployment/service-route.yml | sed --expression='s/${HOST}/'$HOST'/g' | sed --expression='s/${CONTAINER}/'$CONTAINER'/g' | sed --expression='s/${NAMESPACE}/'$NAMESPACE'/g' | kubectl apply -f -'''
							}
						}
					}
				}
            }
	}
    }
}
