pipeline {
	
	agent {
		kubernetes {
    	label 'docker-builder'
    	defaultContainer 'jnlp'
    	yaml """
kind: Pod
spec:
  serviceAccountName: jenkins-agent-account
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    restartPolicy: Never
    command: 
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: swag-license-keys
      mountPath: /licenses
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: swag-license-keys
    persistentVolumeClaim:
      claimName: license-pvc
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials 
          items:
            - key: .dockerconfigjson
              path: config.json 
"""
		}
	}

	parameters{
    	string(name: 'EMPOWER_USER', description: 'Your Empower username')
		string(name: 'EMPOWER_PASSWORD', description: 'Your Empower password')
		string(name: 'DOCKERHUB_USER', description: 'Your Docker hub username')
		string(name: 'DOCKERHUB_PASSWORD', description: 'Your Docker hub password')
	}

	environment {
		PACKAGE="CCBuilder"
        CC_TAG = "10.7"
		TAG = "10.7"
		REG = "docker-registry.registry:5000"
		EMPOWER_USR = "${params.EMPOWER_USER}"
		EMPOWER_PSW = "${params.EMPOWER_PASSWORD}"
		DOCKER_USR = "${params.DOCKERHUB_USER}"
		DOCKER_PWD = "${params.DOCKERHUB_PASSWORD}"
    }

    stages {

		stage('Build') {
			steps {
				container(name: 'kaniko', shell: '/busybox/sh') {
					sh '''#!/busybox/sh
					/kaniko/executor --context ${PACKAGE} \
						--destination ${REG}/commandcentral-builder:${TAG} \
						--insecure-registry docker-registry.registry:5000 \
						--build-arg BUILDER_IMAGE=${CC_REG}/commandcentral-builder:${CC_TAG} \
						--build-arg NODE_IMAGE=${CC_REG}/commandcentral-node:${TAG} \
						--build-arg https://sdc.softwareag.com/dataservewebM107/repository \
						--build-arg https://sdc.softwareag.com/updates/prodRepo \
						--build-arg ${EMPOWER_USR} \
        				--build-arg ${EMPOWER_PSW} \
						--build-arg /licenses/licenses.zip
					'''
				}
			}
		}
    }
}