pipeline {
	
	agent {
		kubernetes {
    	label 'docker-builder'
    	defaultContainer 'jnlp'
    	yaml """
kind: Pod
spec:
  serviceAccountName: jenkins-agent-account
  containers:
  - name: jnlp
    workingDir: /tmp/jenkins
  - name: kaniko
    workingDir: /tmp/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    restartPolicy: Never
    command: 
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: swag-license-keys
      mountPath: /licenses
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: swag-license-keys
    hostPath:
      path: "/tmp/license"
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials 
          items:
            - key: .dockerconfigjson
              path: config.json 
"""
		}
	}

	parameters{

		credentials(credentialType: 'com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl', 
			defaultValue: '', description: 'Empower credentials ', name: 'EMPOWER_CREDENTIALS', required: true)
	}

	environment {
		PACKAGE="CCBuilder"
		CC_REG = "store/softwareag"
        CC_TAG = "10.11"
		TAG = "10.11"
		REG = "docker-registry.registry:5000"
		EMPOWER_CREDS = credentials('EMPOWER_CREDENTIALS')
    }

    stages {

		stage('Prepare') {
			steps {
				container(name: 'kaniko') {
					sh 'mkdir ${PACKAGE}/CCE/licenses; cp /licenses/licenses.zip ${PACKAGE}/CCE/licenses/licenses.zip'
				}
			}
		}
		stage('Build CommandCentral Container') {
			steps {
				container(name: 'kaniko', shell: '/busybox/sh') {
					sh '''#!/busybox/sh
					/kaniko/executor --context ${PACKAGE}/CCE \
						--destination ${REG}/commandcentral-builder:${TAG} \
						--destination ${REG}/commandcentral-builder:${TAG}.${BUILD_NUMBER} \
						--destination ${REG}/commandcentral-builder:latest \
						--insecure-registry docker-registry.registry:5000 \
						--build-arg BUILDER_IMAGE=${CC_REG}/commandcentral-server:${CC_TAG} \
						--build-arg NODE_IMAGE=${CC_REG}/commandcentral-node:${CC_TAG} \
						--build-arg REPO_PRODUCT_URL=https://sdc.softwareag.com/dataservewebM1011/repository \
						--build-arg REPO_FIX_URL=https://sdc.softwareag.com/updates/prodRepo \
						--build-arg REPO_USERNAME=${EMPOWER_CREDS_USR} \
        				--build-arg REPO_PASSWORD=${EMPOWER_CREDS_PSW} \
						--build-arg LICENSES_URL=file:///src/licenses/licenses.zip
					'''
				}
			}
		}

		stage('Build Base Container') {
			steps {
				container(name: 'kaniko', shell: '/busybox/sh') {
					sh '''#!/busybox/sh
					/kaniko/executor --context ${PACKAGE}/Java \
						--destination ${REG}/java:${TAG} \
						--destination ${REG}/java:${TAG}.${BUILD_NUMBER} \
						--destination ${REG}/java:latest \
						--insecure-registry docker-registry.registry:5000 \
						--build-arg BASE_IMAGE=centos:7 \
						--build-arg NODE_IMAGE=${REG}/commandcentral-builder:${TAG}
					'''
				}
			}
		}
    }
}